# Generated by Django 2.0.5 on 2019-07-15 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_investment_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
