# Generated by Django 2.0.5 on 2019-07-17 03:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190714_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='acquired_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='investment',
            name='recent_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
