# Generated by Django 2.0.5 on 2019-07-17 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190716_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='acquired_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='investment',
            name='recent_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
